/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as faucetSol from "./Faucet.sol";
export type { faucetSol };
export type { Greeter } from "./Greeter";
export * as factories from "./factories";
export type { Faucet } from "./Faucet.sol/Faucet";
export { Faucet__factory } from "./factories/Faucet.sol/Faucet__factory";
export { Greeter__factory } from "./factories/Greeter__factory";
